# A configuration for enabling local access to the kafka brokers from the docker host
version: "3.8"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${DOCKER_HOST_NAME}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - DOCKER_HOST_NAME=$(hostname)
    volumes:
      - kafka-persistence:/bitnami/kafka
    # extra_hosts:
      # - mypc:host-gateway
      # - host.docker.internal:host-gateway

  # alpine:
  #   image: alpine:latest
  #   extra_hosts:
  #     - mypc:host-gateway
      # - host.docker.internal:host-gateway

volumes:
  kafka-persistence:

