name: CI
on: 
    push: 
        branches: 
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - uses: actions/setup-node@v3
              with:
                node-version: 20.x
                cache: "foo"
                cache-dependency-path: "build-ci-publish-example/pnpm-lock.yaml"
            - run: cd build-ci-publish-example && pnpm install --frozen-lockfile
            - run: cd build-ci-publish-example && pnpm run ci
